@startuml AntiChewEffect/wearoff
hide footbox

participant ":AntiChewEffect" as effect
participant "insect:Insect" as target

-> effect : remove()
activate effect

effect -> target : getAntiChewCount()
activate target
return antiChewCount

effect -> target : setAntiChewCount(antiChewCount - 1)
activate target
return

return

@enduml