@startuml AntiChewEffect/wearoff
hide footbox

participant ":AntiChewEffect" as effect
participant "target:Insect" as target

-> effect : remove()
activate effect

effect -> target : setAntiChewCount(getAntiChewCount() - 1)
activate target
return

return

@enduml