@startuml Mycelium/grow-sources-targets
hide footbox

actor Mycologist
participant ":Fungus" as fungus
collections "mycelia:Mycelium" as mycelia
collections "mushrooms:Mushroom" as mushrooms
collections "sources:Tecton" as sources

Mycologist -> fungus : getPotentialMyceliumSources()
activate fungus

fungus -> mycelia : getEnds()
activate mycelia

return ends

fungus -> mushrooms : getLocation()
activate mushrooms

return location

note over fungus: sources = union of ends and location(s)
return sources


Mycologist -> sources : getNeighbors()
activate sources
return targets

@enduml