@startuml Mycelium/mycelium-thickening
hide footbox

actor Time
participant ":Mycelium" as mycelium
participant "species:Fungus" as species

Time -> mycelium : tick(dT)
activate mycelium

opt cooldown == 0    
    alt Growing
        mycelium -> species : myceliumGrowthComplete()
        activate species
        return
    else Chewed
        mycelium -> mycelium : die()
        activate mycelium
            ref over mycelium
                mycelium-death
            end ref
        return 
    end
end

return

@enduml