@startuml MyceliumStates

[*] --> Growing
Growing --> Normal : tick(dT)\n[cooldown == 0]

Normal --> [*] : die()
Growing --> [*] : die()

Normal --> Chewed : chew()
Growing --> Chewed : chew()

Chewed --> [*] : tick(dT)\n[cooldown == 0]
 

@enduml   