@startuml classes
interface IActive
class Tecton
together {
    class Fungus
    class Mycelium
    class Mushroom
    class Spore
}
together {
    class Insect
    abstract InsectEffect
}

IActive : tick()

IActive ()- Tecton
IActive ()- Mushroom
IActive ()- Mycelium
IActive ()- Insect
IActive ()- InsectEffect


Tecton o-- "*" Tecton : neighbors
Tecton "2" -- "*" Mycelium
Tecton *-- "*" Spore
Tecton "1" *--o "0..1" Mushroom
Tecton : growMushroom(Fungus)
Tecton : growMycelium(Fungus, Tecton)

Mushroom : burstSpore(Tecton)

Mycelium o-- Fungus

Insect *--o "0..*" InsectEffect
Insect -- "1" Tecton
Insect : eatSpore()
Insect : moveTo(Tecton)
Insect : chewMycelium(Mycelium)

Spore o-- Fungus

InsectEffect <-- Spore

Fungus -- Mushroom
@enduml