@startuml
participant Tecton as Dying
participant Tecton as Neighbors order 100
participant Insect as Insects order 101

-> Dying : tick()
opt break

Dying -> Neighbors : removeNeighbor(self)

create Tecton as New1
Dying -> New1 : newMe()
Dying -> New1 : fillWithStuff(...)

' set location on moved objects ...
Dying -> Insects : setLocation(tecton)

' unsubscribe from tick
<- Dying : unsubscribe(self)

Dying -> Dying !!
end

@enduml