@startuml ParalysingEffect/wearoff
hide footbox

participant ":ParalysingEffect" as effect
participant "insect:Insect" as target

-> effect : remove()
activate effect


'TODO itt gondolom valami másra volt gondolva nem a chewcountra
'       pl setParalysed(false)?
effect -> target : setParalysed(false)
activate target
return

return

@enduml