@startuml Fungus/check-connectivity
hide footbox

participant ":Fungus" as fungus
collections ":Myceilum" as mycelium
collections ":Mushroom" as mushroom

'TODO hmmm, im not sure about this
' self to self?

-> fungus : checkConnectivity()
activate fungus

fungus -> mushroom : getLocation()
activate mushroom
return location

fungus -> mycelium : getEnds()
activate mycelium
return ends


fungus -> mycelium : die()
activate mycelium
return
destroy mycelium

return

@enduml