@startuml Fungus/check-connectivity
hide footbox

participant ":Fungus" as fungus
collections "mycelia:Myceilum" as mycelium
collections "mushrooms:Mushroom" as mushroom

'Dávid:
' hmm, a Fungusnak nincs ilyen függvénye
'!! vagy kerüljön be az osztálydiagramba vagy ne legyen itt
' VAGY mivel ez csak ref ként van, ezért nincs bejövő esemény csak beemeljük már élő lifelineba?
'-> fungus : checkConnectivity()
activate fungus

fungus -> mushroom : getLocation()
activate mushroom
return location

fungus -> mycelium : getEnds()
activate mycelium
return ends

' ezt opt-ba? mert nem mindegyikre hívja meg
' opt feltétele vagy semmi, vagy valami szöveg pl. "disconnected from Mushrooms"
fungus -> mycelium : die()
activate mycelium
return
destroy mycelium

'return

@enduml