@startuml Fungus/grow-mushroom
hide footbox

participant "species:Fungus" as fungus
participant "target:Tecton" as target
collections "spores:Spore" as spore
collections "mycelia:Mycelium" as mycelium
participant "mushroom:Mushroom" as mushroom

-> fungus : growMushroom(target)
activate fungus

fungus -> target: growMushroom(species)
activate target

target -> spore : getSpecies()
activate spore
return species

opt hasEnoughSpores
    target -> mycelium : getSpecies()
    activate mycelium
    return species
    opt hasMycelium
        create mushroom
        target -> mushroom : new(species, target)
        activate mushroom
        return mushroom
    end
end

return mushroom

return success

@enduml
