@startuml ParalysingEffect/wearoff
hide footbox

participant ":ParalysingEffect" as effect
participant "insect:Insect" as target

-> effect : remove()
activate effect

effect -> target : setParalysed(false)
activate target
return

return

@enduml