@startuml

participant ":Insect" as insect
participant "target:Mycelium" as target

-> insect : chewMycelium(target)
activate insect

opt cooldown == 0
    insect -> target : destroy()
    activate target

    ' TODO egyeztetni a diagram nevet
    ref over target
        mycelium_destroy
    end ref

    insect <-- target
    destroy target
end

<-- insect
deactivate insect

@enduml