@startuml Insect/eat-spore
hide footbox

participant "insect:Insect" as insect
participant "location:Tecton" as location
participant "sporeTaken:Spore" as sporeTaken
participant "effect:InsectEffect" as effect

-> insect : eatSpore()
activate insect

opt Idle && CanMove
    insect -> location : takeSpore()
    activate location
    return sporeTaken

    opt sporeTaken exists
        insect -> sporeTaken : getEffect()
        activate sporeTaken

        ref over sporeTaken
            effect-creation
        end ref
        /'    create effect
            sporeTaken -> effect : new()
            activate effect
            return
        end'/

        return effect
        destroy sporeTaken

        opt effect exists
            insect -> effect : applyTo(insect)
            activate effect
            return
        end
    end
end

<-- insect
deactivate insect

@enduml