@startuml
participant ":Insect" as insect
participant "location:Tecton" as location
participant "sporeTaken:Spore" as sporeTaken
participant "effect:InsectEffect" as effect

-> insect : eatSpore()
activate insect

' állapotgép szerint átdolgozni
opt cooldown == 0
    insect -> location : takeSpore()
    activate location

    insect <-- location : sporeTaken
    deactivate location

    opt sporeTaken exists
        insect -> sporeTaken : getEffect()
        activate sporeTaken
        
        ' TODO: effect létrehozás

        insect <-- sporeTaken : effect
        destroy sporeTaken

        insect -> effect : applyTo(self)
        activate effect

        insect <-- effect
        deactivate effect
    end
end

<-- insect
deactivate insect

@enduml