@startuml Insect/move
hide footbox

participant ":Insect" as insect
participant "location:Tecton" as location
participant "target:Tecton" as target


-> insect : moveTo(target)
activate insect

opt Idle && CanMove

    insect -> location : hasMyceliumTo(target)
    activate location

    return moveValid
    deactivate location

    opt moveValid

        insect -> location : removeInsect(self)
        activate location
        return
        
        insect -> target : addInsect(self)
        activate target
        return
    end
end

<-- insect
deactivate insect

@enduml