@startuml InsectStates
skinparam linetype ortho

skinparam Padding 9

' TODO: Az effekteknek nem állapotként kellene szerepelniük
state Alive {
    [*] --> Idle
    Idle --> Active : cooldown > 0
    Active --> Idle : cooldown == 0
    ||
    [*] --> CanMove
    CanMove --> Paralysed : isParalysed
    Paralysed --> CanMove : !isParalysed
    ||
    [*] --> CanChew
    CanChew --> Toothless : antiChewCount > 0
    Toothless --> CanChew : antiChewCount == 0
}
[*] --> Alive

@enduml