@startuml Tecton/absorb-mycelium
hide footbox

actor Time
participant "tecton:MyceliumAbsorbingTecton" as tecton
collections "mycelia: Mycelium" as mycelia


Time -> tecton : tick(dT)
activate tecton

opt absorbtionTimer == 0
    tecton -> mycelia : die()
    activate mycelia

    return
    destroy mycelia
end

tecton -> tecton : super.tick(dT)
activate tecton
return

return

@enduml