@startuml Tecton/special-tecton-classes

class Tecton
class NoMushroomTecton {
    newMe()
    growMushroom(Fungus)
}
class SingleMyceliumTecton {
    newMe()
    canGrowMyceliumFrom(Fungus)
}
class MyceliumAbsorbingTecton {
    cooldown
    newMe()
    tick(dT)
}

Tecton <|-- NoMushroomTecton
Tecton <|-- SingleMyceliumTecton
Tecton <|-- MyceliumAbsorbingTecton

@enduml