@startuml Tecton/tecton-break-seq
hide footbox

participant ":Tecton" as Dying
collections "allNeighbors:Tecton" as allNeighbors
collections "insectsOnMe:Insect" as Insects
participant ":Mushroom" as Mushroom
collections "myceliumsOnMe:Mycelium" as target

-> Dying : tick(dT)
activate Dying
opt Tearing

Dying -> allNeighbors : removeNeighbor(self)
activate allNeighbors
return

create "t1:Tecton" as New1
Dying -> New1 : newMe()
Dying -> New1 : fillWithStuff(...)
activate New1
return
Dying -> allNeighbors : addNeighbor(t1)
activate allNeighbors
return

create "t2:Tecton" as New2
Dying -> New2 : newMe()
Dying -> New2 : fillWithStuff(...)
activate New2
return
Dying -> allNeighbors : addNeighbor(t2)
activate allNeighbors
return

Dying -> Insects : setLocation(t1 or t2)
activate Insects
return

Dying -> Mushroom : setLocation(t1 or t2)
activate Mushroom
return

Dying -> target : die()
activate target

ref over target
    mycelium-death
end ref

return
destroy target

<-- Dying
destroy Dying
end

@enduml