@startuml Tecton/tecton-break-seq
hide footbox

participant "tecton:Tecton" as Dying
collections "neighbors:Tecton" as allNeighbors
collections "mycelia:Mycelium" as target

-> Dying : tick(dT)
activate Dying
opt when breaking

Dying -> allNeighbors : removeNeighbor(tecton)
activate allNeighbors
return

create "t1:Tecton" as New1
Dying -> New1 : newMe()
activate New1
return
Dying -> New1 : fillWithStuff(subset of spores, mushroom or null, subset of insects, subset of neighbors)
activate New1

return

create "t2:Tecton" as New2
Dying -> New2 : newMe()
activate New2
return

Dying -> New2 : fillWithStuff(subset of spores, mushroom or null, subset of insects, subset of neighbors)
activate New2

return

Dying -> target : die()
activate target

return
destroy target

end
return

@enduml