@startuml InsectEffect/effect-wearoff
hide footbox

actor Time
participant "effect:InsectEffect" as effect
participant "insect:Insect" as insect

Time -> effect : tick(dT)
activate effect

opt timeLeft == 0

    effect -> effect : remove()
    activate effect
    return

    effect -> insect : removeEffect(effect)
    activate insect

    return
end

return

@enduml