@startuml SpeedEffect/application
hide footbox

participant ":SpeedEffect" as effect
participant "target:Insect" as target

-> effect : applyTo(target)
activate effect

effect -> target : getSpeed()
activate target
return speed

effect -> target : setSpeed(speed*multiplier)
activate target
return

<-- effect
deactivate effect
@enduml