@startuml SpeedEffect/wearoff
hide footbox

participant ":SpeedEffect" as effect
participant "target:Insect" as target

-> effect : remove()
activate effect

effect -> target : setSpeed(getSpeed() / multiplier)
activate target
return

return

@enduml