@startuml Insect-move/map 
left to right direction
title InsectMove-Map
skinparam linetype polyline
rectangle Skeleton as S

rectangle "s1:Fungus" as s1
rectangle "m1:Mycelium" as m1
rectangle "m2:Mushroom" as m2
rectangle "t1:Tecton" as t1
rectangle "t2:Tecton" as t2
rectangle "t3:Tecton" as t3
rectangle "i1:Insect" as i1
rectangle "i2:Insect" as i2
rectangle "p:ParalysingEffect" as p

S --> t1: 1: new()
S --> t2: 2: new()
S --> t3: 3: new()
S --> t1: 4: addNeighbor(t2)
S --> t2: 5: addNeighbor(t1)
S --> t2: 6: addNeighbor(t3)
S --> t3: 7: addNeighbor(t2)

S --> i1: 8: new(t1)
i1 --> t1 : 8.1: addInsect(i1)
S --> i2: 9: new(t1)
i2 --> t1 : 9.1: addInsect(i2)
S --> p: 10: new()
S --> i2: 11: addActiveEffect(p)
S --> p : 12: applyTo(i2)
p --> i2 : 12.1: setIsParalysed(true)

S -left-> s1: 13: new()
S --> m1: 14: new(s1,t1,t2)
m1 --> t1 : 14.1: addMycelium(m1)
m1 --> t2 : 14.2: addMycelium(m1)
S --> s1: 15. addMycelium(m1)

S --> m2: 16: new(s1, t1)
S --> s1: 17: addMushroom(m2)
S --> t1: 18: addMushroom(m2)


@enduml