@startuml Insect-move/no-mycelium
hide footbox
title INIT: InsectMove-Map

actor Tester as S
participant "i1:Insect" as insect
participant "i1:Insect" as insect
participant "t1:Tecton" as location

S -> insect : moveTo(t3)
activate insect

S <- insect : ask("A rovarnak lejárt a várakozási ideje?")
activate S
return idle

opt idle

    insect -> location : hasMyceliumTo(t3)
    activate location
    location -> my1 : getEnds()
    activate my1
    return [t1, t2] 
    note over location : t3 is neighbor,\nbut no mycelium
    return moveValid = false
end

return

@enduml