@startuml Insect-move/no-myelium
hide footbox
title INIT: InsectMove-Map

actor Tester
'TODO: Skeleton neve :Skeleton vagy csak Skeleton?
participant Skeleton
participant "i1:Insect" as insect
participant "i1:Insect" as insect
participant "t1:Tecton" as location

Tester -> Skeleton
activate Skeleton
Skeleton -> insect : moveTo(t3)
activate insect

Skeleton <- insect : ask("A rovarnak lejárt a várakozási ideje?")
activate Skeleton
return idle

opt idle

    insect -> location : hasMyceliumTo(t3)
    activate location

    'TODO: érték?
    return moveValid = false
end

return
return

@enduml