@startuml Insect-move/paralysed
hide footbox

title INIT: InsectMove-Map

actor Tester as S
participant "i2:Insect" as insect

S -> insect : moveTo(t2)
activate insect
note over insect : insect is paralysed
return
@enduml