@startuml Insect-chew-mycelium/map 
left to right direction

title InsectChewMycelium-Map

rectangle Skeleton as S 

rectangle "fu1:Fungus" as fu1
rectangle "my1:Mycelium" as my1
rectangle "mu1:Mushroom" as mu1
rectangle "t1:Tecton" as t1
rectangle "t2:Tecton" as t2
rectangle "i1:Insect" as i1
rectangle "i2:Insect" as i2
rectangle "i3:Insect" as i3
rectangle "p:ParalysingEffect" as p
rectangle "c:AntiChewEffect" as c

S --> t1: 1: new()
S --> t2: 2: new()
S --> t1: 3: addNeighbor(t2)
S --> t2: 4: addNeighbor(t1)

S --> i1 : 5: new(t1)
i1 --> t1 : 5.1: addInsect(i1)
S --> i2 : 6: new(t1)
i2 --> t1 : 6.1: addInsect(i2)
S --> i3 : 7: new(t1)
i3 --> t1 : 7.1: addInsect(i3)

S --> p : 8: new()
S --> i2 : 9: addActiveEffect(p)
S --> p : 10: applyTo(i2)
p --> i2 : 10.1: setIsParalysed(true)

S --> c : 11: new()
S --> i3 : 12: addActiveEffect(c)
S --> c : 13: applyTo(i3)
c --> i3 : 13.1: getAntiChewCount()
c --> i3 : 13.2: setAntiChewCount(1)



S -left-> fu1: 14: new()
S --> my1: 15: new(fu1,t1,t2)
my1 --> t1 : 15.1: addMycelium(my1)
my1 --> t2 : 15.2: addMycelium(my1)
S --> fu1: 16. addMycelium(my1)

S --> mu1: 17: new(fu1, t1)
S --> fu1: 18: addMushroom(mu1)
S --> t1: 19: setMushroom(mu1)


@enduml