@startuml Insect-chew-mycelium/paralysed
hide footbox
title INIT: InsectChewMycelium-Map

actor Tester as S
participant "i2:Insect" as i2


S -> i2 : chewMycelium(m1)
activate i2
note over i2 : insect is paralysed
return
@enduml