@startuml Insect-chew-mycelium/paralysed
hide footbox
title INIT: InsectChewMycelium-Map

actor Tester
'TODO: Skeleton neve :Skeleton vagy csak Skeleton?
participant Skeleton as S
participant "i2:Insect" as i2


Tester -> S
activate S
S -> i2 : chewMycelium(m1)
activate i2
return
return
@enduml