@startuml Insect-chew-mycelium/toothless
hide footbox
title INIT: InsectChewMycelium-Map

actor Tester as S
participant "i3:Insect" as i3


S -> i3 : chewMycelium(m1)
activate i3
note over i3 : insect is toothless
return
@enduml