@startuml Fungus/check-connectivity
hide footbox

participant ":Fungus" as fungus
collections "mycelia:Myceilum" as mycelium
collections "mushrooms:Mushroom" as mushroom

activate fungus

fungus -> mushroom : getLocation()
activate mushroom
return location

fungus -> mycelium : getEnds()
activate mycelium
return ends


loop for each item in mycela
    opt disconnected
        fungus -> mycelium : die()
        activate mycelium
        return
        destroy mycelium
    end
end

@enduml