@startuml class
package model {
    !include ../SeqAndClassDiagrams/classes.puml
}
!include controller.puml 
package view{

class Cell{
    int x
    int y
    {static} int size
    draw()
}
class Map{
    draw()
    getNeighbors(Cell cell) : cell[]
    cellAt(int x, int y) : Cell
}

class VTecton{
    breaking(Tecton a, Tecton b)
    getColor() : color
}
VTecton "1" --> "tecton 1" Tecton

interface IIcon{
    {abstract} getIcon() : icon or null if dead
    {abstract} getType() : Class
}
class VMycelium{}
VMycelium "2" --> "mycelium 1" Mycelium
class VInsect{
    move(Cell cell)
    eat(Cell cell)
    chew(Cell cell)
}
VInsect "1" --> "insect 1" Insect
class VSpore{}
VSpore "1" --> "spore 1" Spore
class VMushroom{
    burst(Cell cell)
}
VMushroom "1" --> "mushroom 1" Mushroom
class VFungus{
    growMushroom(Cell cell)
    growMycelium(Cell cell, Cell cell)
}
VFungus "1" --> "fungus 1" Fungus
class VColony{}
VColony "1" --> "colony 1" Colony


class View{
    'called by clock
    redraw()
    'sound effect
    {static} notifyUser()
    click(int x, int y)
}
View "1" --> "selected 1" Cell
View "1" --> "selectedFungus 1" VFungus
View "1" --> "selectedColony 1" VColony
Controller "1" --> "view 1" View
}

View --> "map 1" Map
View --> "tectons *" VTecton

Cell "cells *" <-- "1" Map
Cell "cell 1" -- "item 1" IIcon
Cell "cells *" -- "tecton 1" VTecton

IIcon <|-- VMycelium
IIcon <|-- VInsect
IIcon <|-- VSpore
IIcon <|-- VMushroom
@enduml