@startuml AntiChewEffect/application
hide footbox

participant ":AntiChewEffect" as effect
participant "target:Insect" as target

-> effect : applyTo(target)
activate effect

effect -> target : getAntiChewCount()
activate target
return antiChewCount

effect -> target : setAntiChewCount(antiChewCount + 1)
activate target
return

<-- effect
deactivate effect
@enduml