@startuml
participant ":Mushroom" as shroom
participant "location:Tecton" as location
participant "target:Tecton" as target
participant ":Spore" as spore

-> shroom : burstSpore(target)
activate shroom

opt Ready
    shroom -> location : distanceTo(target)
    activate location

    shroom <-- location : distance
    deactivate location

    opt distance <= range
        create spore
        shroom -> spore : new(fungus)
        activate spore

        shroom <-- spore
        deactivate spore

        shroom -> target : addSpore(spore)
        activate target

        shroom <-- target
        deactivate target

        opt sporeCount == 0
            ref over shroom
                mushroom-death
            end ref 
        end
    end
end

'we sure about this? - what if it dies before??
<-- shroom : success

deactivate shroom

@enduml