@startuml Mushroom/get-target-tecton
hide footbox

actor Mycologist

participant ":Mushroom" as mushroom
participant "location:Tecton" as location
collections "closeNeighbors:Tecton" as neighbors

Mycologist -> mushroom : getPotencialBurstTargets()
activate mushroom

mushroom -> location : getNeighbors()
activate location

return closeNeighbors

opt range == 2
    mushroom -> neighbors : getNeighbors()
    activate neighbors
    return farNeighbors
end

note over mushroom: neighbors = union of closeNeighbors and farNeighbors
return neighbors

@enduml