@startuml mushroom_death

participant ":Mushroom" as mushroom
participant "location:Tecton" as location
participant ":Fungus" as fungus

'self to self?
-> mushroom : die()
activate mushroom

mushroom -> location : removeMushroom(mushroom)
activate location
mushroom <-- location 
deactivate location

mushroom -> fungus : removeMushroom(mushroom)
activate fungus
ref over fungus
    check_connevitity 
end ref

mushroom <-- fungus 

deactivate fungus

destroy mushroom

@enduml