@startuml MushroomStates
'skinparam linetype ortho

[*] --> Growing
Growing --> Ready : cooldown == 0
Ready --> SporeBursting : burstSpore()
SporeBursting --> Recharging : if not dying
Recharging --> Ready : cooldown == 0
SporeBursting --> [*] : die()

@enduml