@startuml MushroomStates

state Growing
state Ready
state Recharging
state SporeBursting <<choice>>

[*] --> Growing
Growing --> Ready : tick(dT)\n[cooldown == 0]
Ready --> SporeBursting : burstSpore(tecton)
SporeBursting --> Recharging : [sporeCount != 0]
Recharging --> Ready : tick(dT)\n[cooldown == 0]
SporeBursting --> [*] : [sporeCount == 0]

@enduml