@startuml Insect-chew-mycelium/!can-move
hide footbox
title INIT: EatSpore-Map!CanMove

actor Tester as S
participant "i1:Insect" as i1

S -> i1 : eatSpore()
activate i1
note over i1 : insect is paralysed
return

@enduml