@startuml Eat-spore/get-get-anticheweffect
hide footbox

title INIT: EatSpore-MapSuccess

actor Tester as S

participant "i1:Insect" as i1
participant "t1:Tecton" as t1
participant "sp1:Spore" as sp1
participant "c:AntiChewEffect" as c
participant "e:InsectEffect" as e

S -> i1 : eatSpore()
activate i1

S <- i1 : ask("A rovarnak lejárt a várakozási ideje?")
activate S
return idle

opt idle
    i1 -> t1 : takeSpore()
    activate t1

    return sp1

    i1 -> sp1 : getEffect()
    note over e : static function call
    activate sp1

    sp1 -> e : createEffect()
    activate e

    create c
    e -> c : new()
    activate c

    return c

    return c
    return c
    destroy sp1

    i1 -> c : applyTo(i1)
    activate c
    c -> i1 : getAntiChewCount()
    activate i1
    return 0

    c -> i1 : setAntiChewCount(1)
    activate i1
    return

    return

    return
    
    S -> S : ask("A rovarnak lejárt a várakozási ideje?")
    activate S
    return over

    opt over
        S -> c : tick(more then enough time)
        activate c

        c -> c : remove()
        activate c
        
        c -> i1 : getAntiChewCount()
        activate i1
        return 1

        c -> i1 : setAntiChewCount(0)
        activate i1
        return

        return

        c -> i1 : removeEffect(c)
        activate i1
        return

        return    
    end
end

@enduml