@startuml Eat-spore/map-no-spore
left to right direction
title Eat-spore-MapNoSpore

rectangle Skeleton as S 

rectangle "t1:Tecton" as t1
rectangle "i1:Insect" as i1

S --> t1: 1: new()

S --> i1 : 2: new(t1)

@enduml