@startuml Insect-chew-mycelium/no-spore
hide footbox
title INIT: EatSpore-MapNoSpore

actor Tester as S
participant "i1:Insect" as i1
participant "t1:Tecton" as t1

S -> i1 : eatSpore()
activate i1

note over i1: Insect is not under any effect.
i1 -> t1 : takeSpore()
activate t1

return null

note over i1: sporeTaken does not exists, insect cannot proceed.

return
@enduml