@startuml Absorb-mycelium/map-success
left to right direction
title Absorb-mycelium-MapSuccess

rectangle Skeleton

rectangle "t1:Tecton" as t1
rectangle "t2:MyceliumAbsorbingTecton" as t2
rectangle "s1:Fungus" as s1
rectangle "m1:Mushroom" as m1
rectangle "m2:Mycelium" as m2

Skeleton --> t1: 1: new()
Skeleton --> t2: 2: new()
Skeleton --> t1: 3: addNeighbor(t2)
Skeleton --> t2: 4: addNeighbor(t1)
Skeleton --> s1 : 5: new()
Skeleton --> m1: 6: new(t1, s1)
Skeleton --> t1 : 7: setMushroom(m1)
Skeleton --> s1: 8: addMushroom(m1)
Skeleton --> m2: 9: new(s1, t1, t2)
m2 --> t1 : 9.1: addMycelium(m2)
m2 --> t2 : 9.2: addMycelium(m2)
Skeleton --> t2: 10: addMycelium(m2)

@enduml