@startuml Insect/chew
hide footbox

actor Entomologist
participant ":Insect" as insect
participant "target:Mycelium" as target

Entomologist -> insect : chewMycelium(target)
activate insect

opt CanChew && CanMove && Idle
    insect -> target : die()
    activate target

    ref over target
        mycelium-death
    end ref

    return
    destroy target

    insect -> insect : setCooldown(num)
    activate insect
    return
end

return

@enduml