@startuml Insect/eat-spore
hide footbox

actor Entomologist
participant "insect:Insect" as insect
participant "location:Tecton" as location
participant "sporeTaken:Spore" as sporeTaken
participant "effect:InsectEffect" as effect

Entomologist -> insect : eatSpore()
activate insect

opt Idle && CanMove
    insect -> location : takeSpore()
    activate location
    return sporeTaken

    opt sporeTaken exists
        insect -> sporeTaken : getEffect()
        activate sporeTaken

        ref over sporeTaken
            effect-creation
        end ref

        return effect
        destroy sporeTaken

        opt effect exists
            insect -> effect : applyTo(insect)
            activate effect
            return
        end

            insect -> insect : setCooldown(num)
        activate insect
        return
    end
end

return success

@enduml