@startuml Insect/move
hide footbox

actor Entomologist
participant "insect:Insect" as insect
participant "location:Tecton" as location
participant "target:Tecton" as target

Entomologist -> insect : moveTo(target)
activate insect

opt Idle && CanMove

    insect -> location : hasMyceliumTo(target)
    activate location

    return moveValid

    opt moveValid

        insect -> location : removeInsect(insect)
        activate location
        return
        
        insect -> target : addInsect(insect)
        activate target
        return

        insect -> insect : setCooldown(num)
        activate insect
        return
    end
end

return success

@enduml