@startuml Mycelium/mycelium-thickening
hide footbox

actor Time
participant ":Mycelium" as mycelium
participant ":Fungus" as fungus

Time -> mycelium : tick(dT)
activate mycelium

opt Growing && cooldown == 0
    mycelium -> fungus : myceliumGrowthComplete()
    activate fungus
    return
end

return

@enduml