@startuml Mycelium/mycelium-grow
hide footbox

participant "source:Tecton" as source
participant "target:Tecton" as target
participant "fungus:Fungus" as fungus
participant ":Mycelium" as mycelium

-> source : growMycelium(fungus, target)
activate source

source -> fungus : canGrowMycelium()
activate fungus
return ready
opt ready
    source -> target : distanceTo(source)
    activate target
    return distance
    opt distance == 1
    'TODO MIAFASZ'
        source -> target : canGrowMyceliumFrom(fungus) 
        'check (gombatest or mycelium) and (mycelium species count < limit)
        activate target
        return canGrow

        opt canGrow
            create mycelium
            source -> mycelium : new(fungus,source,target)
            activate mycelium
            return
        end
    end
end
<-- source : success
deactivate source


@enduml
