@startuml Mycelium/mycelium-thickening
hide footbox

participant ":Mycelium" as mycelium
participant ":Fungus" as fungus

-> mycelium : tick(dT)
activate mycelium

opt Growing && cooldown == 0
    mycelium -> fungus : myceliumGrowthComplete()
    activate fungus
    return
end

<-- mycelium
deactivate mycelium

@enduml