@startuml Mycelium/mycelium-grow
hide footbox

actor Mycologist
participant "species:Fungus" as species
participant "source:Tecton" as source
participant "target:Tecton" as target
participant "mycelium:Mycelium" as mycelium

' TODO source, target
Mycologist -> species : growMycelium(source, target)
activate species

species -> species : canGrowMycelium()
activate species
return ready

opt ready
species -> source : growMycelium(species, target)
activate source
    source -> source : canGrowMyceliumFrom(species)
    activate source
    return sourceCanGrow
    source -> target : canGrowMyceliumFrom(species) 
    ' ^check in implementation: (gombatest or mycelium) and (mycelium species count < limit)
    activate target
    return targetCanGrow
    opt sourceCanGrow && targetCanGrow && target is in source.neighbors
        create mycelium
        source -> mycelium : new(species,source,target)
        activate mycelium
        return mycelium
    end
return mycelium
end
return



@enduml
