@startuml Mycelium/mycelium-death
hide footbox

participant "myc:Mycelium" as mycelium
participant "location:Tecton" as location
participant ":Fungus" as fungus

-> mycelium: die()
activate mycelium

mycelium -> location : removeMycelium(myc)
activate location
return


mycelium -> fungus : removeMycelium(myc)
activate fungus
ref over fungus
    check-connectivity
end ref
return

<-- mycelium
destroy mycelium

@enduml