@startuml grow-mycelium-success
hide footbox

title INIT: GrowMycelium-MapSingleMyceliumFail

actor Tester
participant Skeleton
participant "s1:Fungus" as species
participant "t1:Tecton" as source
participant "t2:SingleMyceliumTecton" as target

Tester -> Skeleton
activate Skeleton

Skeleton -> species : growMycelium(t1, t2)
activate species

species -> species : canGrowMycelium()
activate species

Skeleton <- species : ask("Tud még gombafonalat növeszteni a gombafaj?")
activate Skeleton
return ready

return ready

opt ready

    species -> source : growMycelium(t1, t2)
    activate source
        source -> source : canGrowMyceliumFrom(s1)
        activate source
        return sourceCanGrow=true

        source -> target : canGrowMyceliumFrom(s1)
        activate target
        return targetCanGrow=false

        return mycelium=null

    return mycelium=null
end
return success=false

@enduml