@startuml InsectEffect/effect-wearoff
hide footbox

participant "effect:InsectEffect" as effect
participant "insect:Insect" as insect

 -> effect : tick(dT)
activate effect

opt timeLeft == 0


    ref over effect
        wearoff
    end ref

    effect -> insect : removeEffect(effect)
    activate insect

    return
end

return

@enduml