@startuml InsectEffect/effect-creation
hide footbox

participant ":Spore" as spore
participant ":InsectEffect" as effect
participant ":AntiChewEffect" as antichewEffect
participant ":ParalysingEffect" as paralysingEffect
participant ":SpeedEffect" as speedEffect

activate spore

spore -> effect : createEffect()
activate effect

alt random == 1
    create antichewEffect
    effect -> antichewEffect : new()
    activate antichewEffect
    return effect
else random == 2
    create paralysingEffect
    effect -> paralysingEffect : new()
    activate paralysingEffect
    return effect
else random == 3
    create speedEffect
    effect -> speedEffect : new()
    activate speedEffect
    return effect
else random > 3
    ' effect -> effect : effect = null
    note over effect
        effect is null here
    end note
end

return effect

@enduml